spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: dev@sagitta
    password: password@sagitta

  data:
    redis:
      port: 6379
      password: password@sagitta
      timeout: 600ms

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 300000

#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#
#logging:
#  config: classpath:log/logback-dev.xml
#
#loki:
#  distributor:
#    url: http://localhost:3100/loki/api/v1/push
